spring:
  main:
    allow-bean-definition-overriding: true     
    
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} 
  

amazon:
  access:
    key: AKIAY7OWD5SDBTU3QO5Q
    secret-key: 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
  region: ca-central-1
  end-point:
    url: dynamodb.ca-central-1.amazonaws.com
#ribbon timeout
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000